# Generated by Django 2.2.2 on 2019-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakeaddress',
            old_name='suit',
            new_name='suite',
        ),
        migrations.AddField(
            model_name='fakeaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
