# Generated by Django 2.2.2 on 2019-06-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190605_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeaddress',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.FakeUser'),
        ),
        migrations.AlterField(
            model_name='fakecompany',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.FakeUser'),
        ),
        migrations.AlterField(
            model_name='fakegeo',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='users.FakeAddress'),
        ),
    ]
